### ISSUE TITLE
Streaming results have different behavior for same request

### ISSUE THREAD

**Issue by jlowin** [pydantic/pydantic-ai#131]
Here's a contrived example of running the same request with `run()`, `stream()`, and `stream_structured()`. The behavior is quite different.

- `run` produces the expected result.
- `stream_structured` produces an empty dict
- `stream` errors with 

```
ValidationError: 1 validation error for typed-dict
response
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
```

### Code

```python
import asyncio
import pydantic_ai

a = pydantic_ai.Agent(model='openai:gpt-4o', result_type=dict)
request = 'return a dict of 3 fruits and their colors'

async def demo1():
    print('\n--- running demo1 ---\n')
    result = await a.run(request)
    print(result)


async def demo2():
    print('\n--- running demo2 ---\n')
    async with a.run_stream(request) as result:
        async for message in result.stream_structured():
            print(message)


async def demo3():
    print('\n--- running demo3 ---\n')
    async with a.run_stream(request) as result:
        async for message in result.stream():
            print(message)

asyncio.run(demo1())
asyncio.run(demo2())
asyncio.run(demo3())
```

**Comment by samuelcolvin** [comment]
Humm, for me `demo1` and `demo2` are both extremely flakey, with `demo2` less reliable.

But I don't think that's our fault for the most part.

`stream` has to do the validation of the returned data in each step of the iterator, and is raising an error because the returned data isn't valid.

Some background:
* tool calls need an `object` JSON schema with a fixed set of fields
* Some types, e.g. `list[str]` don't produce an `object` schema, so we implicitly convert `list[str]` into `TypedDict('Result', 'response': list[str])`, so we get an `object` schema, 
* then extract the `response` item from the dict

This gets even more problematic for stream responses, where the `response` field is required, so even partial validation fails when it's missing.

I think asking OpenAI for `{'response': {'apple': 'green', ..}` is confusing it. Perhaps we can avoid wrapping the schema in `{'response':{}}` for the case of simple dicts.

**Comment by samuelcolvin** [comment]
I'll note that this works absolutely fine every time for me, so I think it's just OpenAI being bad a creating a dict of this form.

```py
import asyncio
from typing import Any

from devtools import debug
from openai import BaseModel
from pydantic import ValidationError

import pydantic_ai


class Fruit(BaseModel):
    name: str
    color: str


a = pydantic_ai.Agent(model='openai:gpt-4o', result_type=list[Fruit])
request = 'return a dict of 3 fruits and their colors'


async def demo1():
    print('\n--- running demo1 ---\n')
    result = await a.run(request)
    print(result.data)


async def demo2():
    print('\n--- running demo2 ---\n')
    async with a.run_stream(request) as result:
        async for message, last in result.stream_structured():
            try:
                data = await result.validate_structured_result(message, allow_partial=not last)
            except ValidationError as e:
                print('Validation error:', e)
            else:
                print(data)


async def demo3():
    print('\n--- running demo3 ---\n')
    async with a.run_stream(request) as result:
        async for message in result.stream():
            print(message)

asyncio.run(demo1())
asyncio.run(demo2())
asyncio.run(demo3())
```

**Comment by jlowin** [comment]
Ah ok, I'm actually remembering a very similar issue in the early Marvin days (would have been GPT-3.5) with a similar outcome. I believe we solved it by basically yelling at the model via system prompt... wasn't pretty. I agree, I think this is openAI not loving filling out arbitrary objects.
