### ISSUE TITLE
Support OpenRouter

### ISSUE THREAD

**Issue by thisiskeithkwan** [pydantic/pydantic-ai#139]
Openrouter offers simple switing between providers and consolidated billing.

Is it possbile to support openrouter, 
Or can I tweak the code a bit to change the base_url of OpenAI model?

**Comment by samuelcolvin** [comment]
You can already change the URL for `OpenAIModel` by passing a custom client, this is documented: https://ai.pydantic.dev/install/#custom-openai-client.

I'd rather add great support for the most common models that rely on a 3rd party library or service.

**Comment by thisiskeithkwan** [comment]
Thanks Samuel!

**Comment by dhiraj** [comment]
This works great, however one additional problem is that we cannot get the "generation id" from Open Router for further querying costs and token usages; this becomes especially important for streamed requests since the usages field is not present for streamed responses. Is there a way to get Pydantic AI to "pass through" the generation-id from OpenRouter responses?
