### ISSUE TITLE
logfire included in base install

### ISSUE THREAD

**Issue by mplemay** [pydantic/pydantic-ai#205]
Hey, I just wanted to start of by saying - thank you for making this amazing package. Contrary to the installation docs (see https://ai.pydantic.dev/install/), it looks like `logfire-api` is installed with the base version of `pydantic-ai`.

```
matthewlemay@Matthews-Laptop-2 ~/G/brugge (main)> uv add pydantic-ai
Resolved 219 packages in 223ms
   Built brugge @ file:///Users/matthewlemay/Github/brugge
Prepared 3 packages in 230ms
Uninstalled 1 package in 0.71ms
Installed 13 packages in 33ms
 ~ brugge==0.1.0 (from file:///Users/matthewlemay/Github/brugge)
 + cachetools==5.5.0
 + colorama==0.4.6
 + eval-type-backport==0.2.0
 + google-auth==2.36.0
 + griffe==1.5.1
 + groq==0.13.0
 + logfire-api==2.6.2
 + pyasn1==0.6.1
 + pyasn1-modules==0.4.1
 + pydantic-ai==0.0.12
 + pydantic-ai-slim==0.0.12
 + rsa==4.9
```

**Comment by sydney-runkle** [comment]
Hi!

Thanks for your question. `logfire-api` is just a shim for the logfire sdk that does nothing unless `logfire` is installed.

We have this as a dependency so that we can support logfire when installed, but it doesn't do anything until then.

Going to close for now, let me know if you have any follow up questions!

**Comment by mplemay** [comment]
@sydney-runkle Thanks!
