### ISSUE TITLE
Rules for adding extra models

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic-ai#239]
I'm been amazed by how many model providers have come and worked hard to integrate with PydanticAI.

However we can't accept all model contributions going forward, so I want to set some sensible, understandable rules for when we'll accept new models and when we won't. This should hopefully reduce the chances of disappointment and wasted work.

Python package monthly downloads in November for model SDKs:
* OpenAI: 48m
* Cohere: 6m
* Anthropic: 5m
* Gemini: 3.7m (vertexai 700k, google-generativeai 3m)
* Ollama: 1m
* Groq: 850k
* MistralAI: 583k

(numbers from https://pepy.tech/)

I therefore propose we set these rules:
* to add a new model with an extra dependency, that dependency needs > 500k monthly downloads, consistently over 3 months
* to add a new model which uses another models logic internally and has no extra dependencies (e.g. `OllamaModel` which uses `OpenAIModel`), that model's GitHub org needs > 20k stars in total
* for any other model that’s just a custom URL and API key, we’re happy to add a one paragraph description with a link and instructions on the URL to use (I'll alter `OpenAIModel` to make it easier to pass a custom base url)
* for any other model that requires more logic, we recommend you release your own Python package `pydantic-ai-xxx`, which depends on `pydantic-ai-slim` and implements a model that inherits from our `Model` abc

**Comment by jhpiedrahitao** [comment]
Should other metrics be considered more than GitHub stars? like pricing, performance, models offering, etc...

Several providers are top in leaderboards are outside by only taking these into account; I think the [Artificial analysis providers leader board](https://artificialanalysis.ai/leaderboards/providers) can also be taken into account

**Comment by samuelcolvin** [comment]
I think PyPI downloads, while not perfect are a better quantitative measure of whether a model should be added to PydanticAI directly.

**Comment by therealjkvalentine** [comment]
![image](https://github.com/user-attachments/assets/82fd72b3-2b7f-4105-a27a-b0391bc94874)

**Comment by soufianechami** [comment]
@samuelcolvin  Thank you for sharing your perspective. I understand your reasoning and the criteria you've outlined for model contributions. 

That said, I believe there are some unique aspects to SambaNova's LLMs API approach that warrant consideration under these rules.

Our strategic approach differs from the model providers listed. Instead of creating a standalone SDK or PyPI package, our API is fully OpenAI-compatible. This intentional design choice ensures our users can seamlessly integrate SambaNova’s fast inference API into their applications without making significant changes to their existing codebases. As such, our adoption metrics cannot be directly compared to those of providers with separate SDKs like Groq.

For example, if you visit [our official portal](https://cloud.sambanova.ai/apis), the "Get Started" code snippet (shared below) uses only the OpenAI library—no separate "sambanova" library is required. This reflects our focus as an AI chip company prioritizing fast and scalable inference. 

```python
import os
import openai

client = openai.OpenAI(
    api_key=os.environ.get("SAMBANOVA_API_KEY"),
    base_url="https://api.sambanova.ai/v1",
)

response = client.chat.completions.create(
    model='Meta-Llama-3.1-8B-Instruct',
    messages=[{"role":"system","content":"You are a helpful assistant"},{"role":"user","content":"Hello"}],
    temperature=0.1,
    top_p=0.1,
)
print(response.choices[0].message.content)
```

Regarding popularity, we currently have over 500,000 weekly active users leveraging our APIs. Additionally, SambaNova is the only platform enabling users to access large foundational models, such as Llama-3 405B, at no cost and at scale—a capability unmatched by other providers. [Source](https://artificialanalysis.ai/models/llama-3-1-instruct-405b/providers#speed)

Lastly, the "sambanova" package on PyPI is unrelated to our LLM APIs; it serves corporate customers using a different product line.

I hope this clears up any confusion. Please let me know if you have further questions or need additional information. I’m happy to discuss this in more detail.
