### ISSUE TITLE
Agent skipping tool calls if model_response contains text response

### ISSUE THREAD

**Issue by joshcx** [pydantic/pydantic-ai#510]
In the current agent implementation in agent.py, when handling a model's response, if the model's response returns a text part, the tool calls are skipped. Can we have it accept both text responses + tool calls? I would imagine situations like Chain-of-thought implementations might frequently require both text and tool responses.

![Screenshot 2024-12-20 at 3 41 49 PM](https://github.com/user-attachments/assets/c828d650-08db-45a2-96e0-ca3987d50b3e)

https://github.com/pydantic/pydantic-ai/blob/main/pydantic_ai_slim/pydantic_ai/agent.py#L867-#L871

**Comment by sydney-runkle** [comment]
@joshcx,

Thanks for reporting. This potentially could be fixed by https://github.com/pydantic/pydantic-ai/pull/505, though I don't know if that's actually the right solution.

One potential workaround here for now is that if you set `return_type` to a structured type instead of the inferred `str`, then you're guaranteed to have tool calls execute.

You can also use `exit_strategy='exhaustive'` set on the agent, though that doesn't necessarily guarantee a return value sourced from tool calls.

This is especially relevant for Gemini and Anthropic, where heterogenous responses (text and tool calls) are very common.

**Comment by joshcx** [comment]
Thanks for the suggestions @sydney-runkle .

Giving preference to tool calls instead of text responses does seem like a better approach. However, may I understand why we can't do both? i.e. add the text response to the message history then run the tool calls? I'm thinking of chain-of-thought implementations where we would want to include all text responses in subsequent model requests. In my current scenario, the model produces a detailed explanation of its thought process then at the end decides to perform multiple function calls. With #505 , we exclude the thought process entirely, which may affect the model's subsequent actions.
